// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvAWVnh8BuwtEsfrnh6XSr9xKbOpxz9UM',
    appId: '1:1094715114515:android:738164a4cbc7da5df92be6',
    messagingSenderId: '1094715114515',
    projectId: 'attendance-app-b667e',
    databaseURL: 'https://attendance-app-b667e-default-rtdb.firebaseio.com',
    storageBucket: 'attendance-app-b667e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8f5ZX3GWbUYWZ2xlZOcF4Td7e_01xdRw',
    appId: '1:1094715114515:ios:e72b71a2f7bd1cf9f92be6',
    messagingSenderId: '1094715114515',
    projectId: 'attendance-app-b667e',
    databaseURL: 'https://attendance-app-b667e-default-rtdb.firebaseio.com',
    storageBucket: 'attendance-app-b667e.appspot.com',
    iosClientId: '1094715114515-4g7nn82jq8l288um3u8hqtj4vf7ukkou.apps.googleusercontent.com',
    iosBundleId: 'com.example.teacherApp',
  );
}
